<?php

namespace App\Shared\Errors;

enum ErrorCode: string
{
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case UNAUTHENTICATED = 'UNAUTHENTICATED';
    case FORBIDDEN = 'FORBIDDEN';
    case NOT_FOUND = 'NOT_FOUND';
    case INTERNAL_ERROR = 'INTERNAL_ERROR';
    case METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
    case TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
    case HTTP_ERROR = 'HTTP_ERROR';
    case IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED';
    case IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED';
    case REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS';
    case DONOR_DUPLICATE_NIK = 'DONOR_DUPLICATE_NIK';
    case DONOR_DUPLICATE_PHONE = 'DONOR_DUPLICATE_PHONE';
    case DONOR_MERGE_CONFLICT = 'DONOR_MERGE_CONFLICT';
    case DONOR_DEFERRAL_CONFLICT = 'DONOR_DEFERRAL_CONFLICT';
    case DONOR_DEFERRAL_ALREADY_LIFTED = 'DONOR_DEFERRAL_ALREADY_LIFTED';
    case DONOR_ACCOUNT_NOT_LINKED = 'DONOR_ACCOUNT_NOT_LINKED';
    case DONOR_PERMANENT_DEFERRAL_NOT_LIFTABLE = 'DONOR_PERMANENT_DEFERRAL_NOT_LIFTABLE';
    case APPOINTMENT_TRANSITION_REJECTED = 'APPOINTMENT_TRANSITION_REJECTED';
    case BLOOD_BATCH_TRANSITION_REJECTED = 'BLOOD_BATCH_TRANSITION_REJECTED';
    case BATCH_EXPIRY_UNDETERMINABLE = 'BATCH_EXPIRY_UNDETERMINABLE';
    case UNIT_NUMBER_ALLOCATION_FAILED = 'UNIT_NUMBER_ALLOCATION_FAILED';
    case INVENTORY_SEPARATION_REJECTED = 'INVENTORY_SEPARATION_REJECTED';
    case LAB_TEST_NOT_IN_PANEL = 'LAB_TEST_NOT_IN_PANEL';
    case LAB_RESULT_DUPLICATE = 'LAB_RESULT_DUPLICATE';
    case LAB_RESULT_REJECTED = 'LAB_RESULT_REJECTED';
}
